name: BTHE1
favicon: null
layout_spectrum: 0.93867
typography_spectrum: 0.5058702901005745
title: BTHE1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f6'
    - '#898584'
    - '#eabd93'
    - '#2c1908'
    - '#545d6c'
  brandStrength: 0.5625
  lightness: 0.5779111846350133
  saturation: 0
  rhythmicContrast: 0.559783365111798
purpose: []
