name: BTHE1
favicon: null
layout_spectrum: 0.74865
typography_spectrum: 0.35915
title: BTHE1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#37433f'
    - '#030301'
    - '#eba67a'
    - '#7f7f81'
  brandStrength: 0.5625
  lightness: 0.5779111846350133
  saturation: 0
  rhythmicContrast: 0.559783365111798
purpose: []
