name: BTHE1
favicon: null
layout_spectrum: 0.6176484804600477
typography_spectrum: 0.5058702901005745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7405735591892153
  lightness: 0.5779111846350133
  saturation: 0.10225190198980272
  rhythmicContrast: 0.559783365111798
purpose: []
